---
title: "Covid_trend_project"
author: "Mary Boateng"
date: "2025-07-04"
output: html_document
---

#Step 1: Set Working Directory
setwd("C:/Users/mboat/OneDrive/covid_trend_Project")
list.files()


#Step 2: Load Required Packages
library(tidyverse)

#Step 3: Import the COVID-19 Dataset
covid_data <- read.csv("owid-covid-data.csv.csv")

#Step 4: Preview and Understand the Data
head(covid_data)
colnames(covid_data)

# Step 5: Filter Data for US, India, and Brazil (2022 and beyond)
covid_selected <- covid_data %>%
  filter(location %in% c("United States", "India", "Brazil"),
         date >= "2022-01-01") %>%
  select(date, location, new_cases)

#cleaning data; removing all 0 and missing values 

covid_clean <- covid_selected %>%
  filter(!is.na(new_cases), new_cases != 0)

#converting date column from a character to a proper Date format,

covid_clean$date <- as.Date(covid_clean$date)


# Step 6: Create Line Graph of Daily New Cases with ggplot2

ggplot(covid_clean, aes(x = date, y = new_cases, color = location)) +
  geom_line(size = 1) +
  labs(title = "COVID-19 New Cases Over Time after 2022",
       x = "Date",
       y = "New Cases",
       color = "Country") +
  theme_minimal()


# Interprations of Line graph
    # The line graph shows daily new Covid-19 cases in the US, India and Brazil starting from january 2022
    #Across all countries there is a noticable spike in early 2022, which correlates to the spread of the omnicron variant, after this peak there are daily declines in case number, however each country has it own unqiue flucations that shwocase local surges and from public health policies 
    # The removal of zeroes and missing values, made trends more cleaer and focused on periods of active transmission
    # This line graph provides a visual comparsion of the evolution of the pandemic across counties with large population and various healthcare infastrcuture 
